(function() {

	'use strict';

	BX.namespace('BX.Landing.Component');

	let announceTimerId = null;
	let pendingAnnouncement = null;

	const errorTexts = (container) => [...container.querySelectorAll('.landing-demo-error')]
		.map((error) => error.textContent.trim())
		.filter((error) => error !== '');

	// keeps only the last pending message so racing filter applies don't queue stale announcements
	const announce = (message, politeness) =>
	{
		pendingAnnouncement = {message: message, politeness: politeness};

		if (announceTimerId !== null)
		{
			clearTimeout(announceTimerId);
		}

		announceTimerId = setTimeout(() =>
		{
			announceTimerId = null;
			const announcement = pendingAnnouncement;
			pendingAnnouncement = null;

			if (announcement === null)
			{
				return;
			}

			BX.Runtime.loadExtension('ui.a11y')
				.then((exports) =>
				{
					exports.LiveAnnouncer.announce(announcement.message, announcement.politeness);
				})
				// the announcement is an addition to the visible list: a missing extension must not throw
				.catch(() => {});
		}, 500);
	};

	BX.Landing.Component.Demo = function()
	{
		this.wrapper = BX('grid-tile-wrap');
		this.inner = BX('grid-tile-inner');
		this.navigation = BX('landing-demo-navigation');
		this.workarea = BX('workarea-content') || BX('air-workarea-content');
		this.errors = BX('landing-demo-errors');
		this.loader = new BX.Loader();

		// the indicator carries no text, so it is a visual cue only: the outcome is what gets announced
		if (this.loader.layout)
		{
			this.loader.layout.setAttribute('data-testid', 'landing-demo-loader');
		}

		// an alert region already holding its text at parse time is never announced on its own
		const initialErrors = this.errors ? errorTexts(this.errors) : [];
		if (initialErrors.length > 0)
		{
			announce(initialErrors.join('. '), 'assertive');
		}

		if (!this.wrapper || !this.inner)
		{
			return;
		}

		if (!this.navigation)
		{
			this.navigation = BX.create('div', {
				props: {
					id: 'landing-demo-navigation',
					className: 'landing-navigation',
				}
			});
			BX.Dom.insertAfter(this.navigation, this.wrapper);
		}

		// show title
		this.startHeight = 0;
		this.tileTitleOpened = null;
		this.tileTitleHideTimeout = null;
		this.tileTitleHidingTile = null;

		// event handlers
		this.onTileTitleClick = this.onTileTitleClick.bind(this);
		this.onTileTitleLeave = this.onTileTitleLeave.bind(this);
		this.onTileTitleKeyDown = this.onTileTitleKeyDown.bind(this);
		this.onPseudoLinkClick = this.onPseudoLinkClick.bind(this);

		this.init();

		// event on app install
		top.BX.addCustomEvent(
			top,
			'Rest:AppLayout:ApplicationInstall',
			BX.delegate(this.onAppInstall, this)
		);

		BX.addCustomEvent(
			'BX.Main.Filter:apply',
			BX.delegate(this.onFilterApply, this)
		);

		BX.addCustomEvent(
			'BX.Main.Filter:beforeApply',
			BX.delegate(this.onBeforeFilterApply, this)
		);
	};

	BX.Landing.Component.Demo.CLASS_TILE = 'landing-item';
	BX.Landing.Component.Demo.CLASS_DESC_OPEN = 'landing-item-desc-open';

	BX.Landing.Component.Demo.prototype =
	{
		init: function()
		{
			// links handlers
			this.links = [].slice.call(this.inner.querySelectorAll('.landing-template-pseudo-link'));
			this.bindPseudoLinks();

			if (BX.Landing.Component.Demo.createEmptyId)
			{
				const toolbar = BX.UI.ToolbarManager.getDefaultToolbar();
				if (toolbar)
				{
					this.linkEmpty = toolbar.getButton(BX.Landing.Component.Demo.createEmptyId);
					if (this.linkEmpty)
					{
						BX.Event.bind(this.linkEmpty.button, 'click', this.onPseudoLinkClick);
					}
				}
			}

			// tiles
			this.tiles = [].slice.call(this.inner.querySelectorAll('.' + BX.Landing.Component.Demo.CLASS_TILE));
			this.createTileList();
			this.bindTileTitles();
		},

		reinit: function()
		{
			this.flushTileTitleHide();
			this.unbindPseudoLinks();
			this.unbindTileTitles();

			this.tiles = [];
			this.links = [];
			this.tileTitleOpened = null;

			this.init();
		},

		// a tile blocked by the tariff opens the restriction popup instead of the preview slider; the
		// popup code is generated by the server, so it is bound here to survive a grid rebuild
		bindPseudoLinks: function()
		{
			this.links.forEach(link => {
				if (BX.Dom.hasClass(link, 'landing-item-payment'))
				{
					if (BX.Landing.Component.Demo.restrictionHandler)
					{
						BX.Event.bind(link, 'click', BX.Landing.Component.Demo.restrictionHandler);
					}
				}
				else
				{
					BX.Event.bind(link, 'click', this.onPseudoLinkClick);
				}
			});
		},

		unbindPseudoLinks: function()
		{
			this.links.forEach(link => {
				if (BX.Dom.hasClass(link, 'landing-item-payment'))
				{
					if (BX.Landing.Component.Demo.restrictionHandler)
					{
						BX.Event.unbind(link, 'click', BX.Landing.Component.Demo.restrictionHandler);
					}
				}
				else
				{
					BX.Event.unbind(link, 'click', this.onPseudoLinkClick);
				}
			});
		},

		onPseudoLinkClick: function(event)
		{
			const link = event.currentTarget;
			const sliderHref = link.dataset.href;
			if (!sliderHref)
			{
				return;
			}

			// the user asked for a native navigation: leave the new tab or window to the browser
			if (event.ctrlKey || event.metaKey || event.shiftKey || event.altKey || event.button > 0)
			{
				return;
			}

			// the tile is a real link, the preview belongs to the slider
			event.preventDefault();

			BX.SidePanel.Instance.open(sliderHref, {
				allowChangeHistory: false,
				width: link.dataset.sliderWidth ? parseInt(link.dataset.sliderWidth) : null,
				data: {
					rightBoundary: 0,
				},
				customLeftBoundary: 60,
				events: {
					onClose: function (eventClosed)
					{
						const openerSliderPath = sliderHref.split('?')[0];
						const currentSliderPath = eventClosed.slider.iframeSrc.split('?')[0];
						if (openerSliderPath !== currentSliderPath && sliderHref.indexOf('frameMode=Y') < 0)
						{
							top.location.reload();
						}
					},
				},
			});
		},

		createTileList: function ()
		{
			new BX.Landing.TileGrid({
				wrapper: this.wrapper,
				inner: this.inner,
				tiles: this.tiles,
				sizeSettings : {
					minWidth : 250,
					maxWidth: 281
				}
			});
		},

		bindTileTitles: function ()
		{
			this.tiles.forEach(tile =>
			{
				const openBtn = tile.querySelector('.' + BX.Landing.Component.Demo.CLASS_DESC_OPEN);
				if (openBtn)
				{
					BX.Event.bind(openBtn, 'click', this.onTileTitleClick);
					BX.Event.bind(tile, 'keydown', this.onTileTitleKeyDown);
					BX.Event.bind(tile, 'mouseleave', this.onTileTitleLeave);
				}

			}, this);
		},

		unbindTileTitles: function ()
		{
			this.tiles.forEach(tile =>
			{
				const openBtn = tile.querySelector('.' + BX.Landing.Component.Demo.CLASS_DESC_OPEN);
				if (openBtn)
				{
					BX.Event.unbind(openBtn, 'click', this.onTileTitleClick);
					BX.Event.unbind(tile, 'keydown', this.onTileTitleKeyDown);
					BX.Event.unbind(tile, 'mouseleave', this.onTileTitleLeave);
				}

			}, this);
		},

		onTileTitleClick: function(event)
		{
			event.preventDefault();
			const tile = event.currentTarget.closest('.' + BX.Landing.Component.Demo.CLASS_TILE);
			if (this.tileTitleOpened === tile)
			{
				this.hideTileTitle(tile);
			}
			else
			{
				this.showTileTitle(tile);
			}
		},

		onTileTitleKeyDown: function(event)
		{
			const tile = event.currentTarget;
			if (event.key !== 'Escape' || this.tileTitleOpened !== tile)
			{
				return;
			}

			// the description is the innermost thing open here: the slider around must not close too
			event.preventDefault();
			event.stopPropagation();

			this.hideTileTitle(tile);
			tile.querySelector('.' + BX.Landing.Component.Demo.CLASS_DESC_OPEN).focus();
		},

		onTileTitleLeave: function(event)
		{
			this.hideTileTitle(event.currentTarget);
		},

		showTileTitle : function(tile)
		{
			// a collapse still waiting for its timeout would strip the class from the tile reopened
			// inside that window, so it is finished here instead of firing later
			this.flushTileTitleHide();

			if (this.tileTitleOpened)
			{
				this.hideTileTitle(this.tileTitleOpened);
			}

			const descInner = tile.querySelector('.landing-item-desc-inner');
			const descHeightBlock = tile.querySelector('.landing-item-desc-height');

			// the collapsed height is what the next collapse animates back to: it is read before the
			// class of the open state touches the description
			this.startHeight = BX.style(descInner, 'height');
			tile.classList.add('landing-tile-title-show');
			descInner.style.height = descHeightBlock.offsetHeight + 'px';

			this.tileTitleOpened = tile;
			this.setTileTitleExpanded(tile, true);
		},

		hideTileTitle: function (tile)
		{
			if (this.tileTitleOpened !== tile)
			{
				return;
			}

			const descInner = tile.querySelector('.landing-item-desc-inner');
			descInner.style.height = this.startHeight;

			this.tileTitleHidingTile = tile;
			this.tileTitleHideTimeout = setTimeout(() =>
			{
				this.tileTitleHideTimeout = null;
				this.tileTitleHidingTile = null;
				this.completeTileTitleHide(tile);
			}, 230);

			this.tileTitleOpened = null;
			this.setTileTitleExpanded(tile, false);
		},

		// the height animation is over by now, the open state of the tile can be dropped
		completeTileTitleHide: function(tile)
		{
			if (!tile)
			{
				return;
			}

			tile.classList.remove('landing-tile-title-show');

			const descInner = tile.querySelector('.landing-item-desc-inner');
			if (descInner)
			{
				descInner.style.paddingTop = 0;
				descInner.style.marginBottom = 0;
			}
		},

		flushTileTitleHide: function()
		{
			if (this.tileTitleHideTimeout === null)
			{
				return;
			}

			clearTimeout(this.tileTitleHideTimeout);
			this.tileTitleHideTimeout = null;

			const tile = this.tileTitleHidingTile;
			this.tileTitleHidingTile = null;
			this.completeTileTitleHide(tile);
		},

		// aria-expanded is the only state the assistive technology reads, the class stays visual
		setTileTitleExpanded: function(tile, expanded)
		{
			const openBtn = tile.querySelector('.' + BX.Landing.Component.Demo.CLASS_DESC_OPEN);
			if (openBtn)
			{
				openBtn.setAttribute('aria-expanded', expanded ? 'true' : 'false');
			}
		},

		// the id of the tile lives on its interactive element, not on the tile itself
		tileControlId: function(element)
		{
			const tile = element.closest ? element.closest('.' + BX.Landing.Component.Demo.CLASS_TILE) : null;
			const control = tile ? tile.querySelector('.landing-demo-tile-link[id]') : null;

			return control ? control.id : null;
		},

		controlKeyOf: function(element)
		{
			if (element.dataset && element.dataset.testid)
			{
				return {type: 'testid', value: element.dataset.testid};
			}

			if (element.id)
			{
				return {type: 'id', value: element.id};
			}

			const firstClass = element.classList && element.classList.length > 0 ? element.classList[0] : null;

			return {
				type: 'tag',
				value: element.tagName.toLowerCase(),
				className: firstClass,
			};
		},

		findControl: function(container, controlKey)
		{
			if (controlKey.type === 'testid')
			{
				return [...container.querySelectorAll('[data-testid]')]
					.find((element) => element.dataset.testid === controlKey.value)
					|| null;
			}

			if (controlKey.type === 'id')
			{
				const element = document.getElementById(controlKey.value);

				return element && container.contains(element) ? element : null;
			}

			const elements = [...container.getElementsByTagName(controlKey.value)];
			if (!controlKey.className)
			{
				return elements[0] || null;
			}

			return elements.find((element) => element.classList.contains(controlKey.className)) || null;
		},

		saveFocusAnchor: function()
		{
			const active = document.activeElement;
			if (!active || !this.inner.contains(active))
			{
				return null;
			}

			return {
				tileId: this.tileControlId(active),
				controlKey: this.controlKeyOf(active),
			};
		},

		restoreFocusAnchor: function(anchor)
		{
			// the filter field keeps the focus it had while typing: nothing to restore inside the list
			if (!anchor)
			{
				return;
			}

			let target = null;
			// marketplace template ids carry slashes and dots, so they are unusable in css selectors
			const control = anchor.tileId ? document.getElementById(anchor.tileId) : null;
			const tile = control && this.inner.contains(control)
				? control.closest('.' + BX.Landing.Component.Demo.CLASS_TILE)
				: null;
			if (tile)
			{
				target = this.findControl(tile, anchor.controlKey);
			}
			else if (!anchor.tileId)
			{
				// a service tile carries no template link to anchor to, so its control is looked up
				// across the whole grid instead; a template tile whose id no longer resolves must not
				// come here, its control key is shared by every tile and would match a foreign template
				target = this.findControl(this.inner, anchor.controlKey);
			}

			if (!target)
			{
				target = this.inner;
				if (!this.inner.hasAttribute('tabindex'))
				{
					this.inner.setAttribute('tabindex', '-1');
				}
			}

			target.focus({preventScroll: true});
		},

		onAppInstall: function(installed)
		{
			window.location.reload();
		},

		onBeforeFilterApply: function()
		{
			this.loader.show(this.workarea);
		},

		// every tile of a template carries this class, the service tiles of the grid do not
		countTiles: function()
		{
			return this.inner.querySelectorAll('.landing-demo-tile-link').length;
		},

		// the error region stays outside the replaced grid, so the response is carried into it by
		// hand; it is in the dom from the first render, which is what makes its role="alert" fire
		updateErrors: function(result)
		{
			if (!this.errors)
			{
				return;
			}

			const errors = result.querySelector('#landing-demo-errors');
			const texts = errors ? errorTexts(errors) : [];
			// role="alert" reads the region out on every rewrite, so an unchanged error is left alone
			if (errorTexts(this.errors).join('\n') !== texts.join('\n'))
			{
				this.renderErrors(texts);
			}
		},

		// the region is rebuilt from text, never from response markup: it is a live region of the
		// document, where anything inserted as html would run
		renderErrors: function(texts)
		{
			if (!this.errors)
			{
				return;
			}

			BX.Dom.clean(this.errors);
			texts.forEach((text) =>
			{
				BX.Dom.append(
					BX.create('p', {props: {className: 'landing-demo-error'}, text: text}),
					this.errors
				);
			});
		},

		refreshFailed: function(promise)
		{
			// a failed refresh has nothing to report but itself: an error left from the previous
			// response would be read after the announcement as if it were the current one
			this.renderErrors([]);
			announce(BX.message('LANDING_TPL_LIST_UPDATE_ERROR'), 'assertive');
			promise.fulfill();
			this.loader.hide();
		},

		onFilterApply: function(filterId, values, filterInstance, promise, params)
		{
			if (params)
			{
				params.autoResolve = false;
			}

			BX.ajax({
				method: 'POST',
				dataType: 'html',
				url: BX.Landing.Component.Demo.ajaxPath,
				onsuccess: data => {
					const result = BX.Dom.create('div', {html: data});
					const grid = result.querySelector('#grid-tile-inner');
					// a fatal or an auth redirect answers with a page that carries no grid at all
					if (!grid)
					{
						this.refreshFailed(promise);

						return;
					}

					// the anchor is taken after the response arrives and before the content is replaced
					const anchor = this.saveFocusAnchor();
					this.inner.innerHTML = grid.innerHTML;

					const navigation = result.querySelector('#landing-demo-navigation');
					if (navigation)
					{
						this.navigation.innerHTML = navigation.innerHTML;
					}
					else
					{
						BX.Dom.clean(this.navigation);
					}

					this.updateErrors(result);
					this.reinit();
					this.restoreFocusAnchor(anchor);
					announce(
						BX.message('LANDING_TPL_LIST_UPDATED').replace('#COUNT#', this.countTiles()),
						'polite'
					);
					promise.fulfill();
					this.loader.hide();
				},
				onfailure: () => {
					this.refreshFailed(promise);
				},
			});
		},
	};

})();

BX.ready(function ()
{
	new BX.Landing.Component.Demo();
});
